
import java.awt.Component;
import java.awt.Panel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author dalas
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Connection conexion;
    private String usuario = "";
    DefaultListModel<String> modelo = new DefaultListModel<>();
    private int idAlumnoSeleccionado;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        try {
            // Establecer la conexión
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/adminescuela", "root", "");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoUsuario = new javax.swing.ButtonGroup();
        telefono5 = new javax.swing.JLabel();
        Jpanels = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        secretaria1 = new javax.swing.JRadioButton();
        direccion1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputApellidos1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputNombre1 = new javax.swing.JTextPane();
        javax.swing.JLabel jLabel28 = new javax.swing.JLabel();
        Secretaria = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Listasecretaria = new javax.swing.JList<>();
        jLabel29 = new javax.swing.JLabel();
        mostrarAlumnos = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        curso = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        inputcursonuevo = new javax.swing.JTextPane();
        cambiarcurso = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Direccion = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDireccion = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        apellidoo = new javax.swing.JLabel();
        telefono1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        telefono2 = new javax.swing.JLabel();
        telefono3 = new javax.swing.JLabel();
        telefono4 = new javax.swing.JLabel();
        amonestacion = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();

        tipoUsuario.add(secretaria1);
        tipoUsuario.add(direccion1);

        direccion1.setActionCommand("Direccion");

        secretaria1.setActionCommand("Secretaria");

        telefono5.setBackground(new java.awt.Color(0, 0, 0));
        telefono5.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        telefono5.setForeground(new java.awt.Color(255, 255, 255));
        telefono5.setText("Email:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanels.setLayout(new java.awt.CardLayout());

        Inicio.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Sitka Heading", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ADMINSTRACION ESCUELA");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Secretaría");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setOpaque(true);
        jLabel10.setVerifyInputWhenFocusTarget(false);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Dirección");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.setOpaque(true);
        jLabel11.setVerifyInputWhenFocusTarget(false);

        secretaria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretaria1ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOMBRE");

        jLabel13.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("APELLIDOS");

        inputApellidos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(inputApellidos1);

        inputNombre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(inputNombre1);

        jLabel28.setBackground(new java.awt.Color(153, 153, 153));
        jLabel28.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Acceder");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.setOpaque(true);
        jLabel28.setVerifyInputWhenFocusTarget(false);
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarUsuario(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secretaria1)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccion1)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(306, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(289, 289, 289)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(direccion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addComponent(secretaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)))
        );

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel9))
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        Jpanels.add(Inicio, "card2");

        Secretaria.setBackground(new java.awt.Color(153, 153, 153));
        Secretaria.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SecretariaComponentShown(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(153, 153, 153));
        jLabel15.setFont(new java.awt.Font("Sitka Heading", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Panel de Secretaría");

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        Listasecretaria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Listasecretaria.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListasecretariaComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(Listasecretaria);

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Alumnos");

        mostrarAlumnos.setText("Mostrar");
        mostrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAlumnosActionPerformed(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Sitka Subheading", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Cambiar Curso:");

        curso.setBackground(new java.awt.Color(0, 0, 0));
        curso.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        curso.setForeground(new java.awt.Color(255, 255, 255));
        curso.setText(".");

        jLabel31.setBackground(new java.awt.Color(0, 0, 0));
        jLabel31.setFont(new java.awt.Font("Sitka Subheading", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Curso:");

        inputcursonuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane6.setViewportView(inputcursonuevo);

        cambiarcurso.setText("Cambiar");
        cambiarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarcursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mostrarAlumnos)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(curso)
                    .addComponent(jLabel31)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarcurso))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(mostrarAlumnos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(curso)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cambiarcurso)))
                .addGap(19, 19, 19))
        );

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Volver");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setOpaque(true);
        jLabel14.setVerifyInputWhenFocusTarget(false);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverainicio(evt);
            }
        });

        javax.swing.GroupLayout SecretariaLayout = new javax.swing.GroupLayout(Secretaria);
        Secretaria.setLayout(SecretariaLayout);
        SecretariaLayout.setHorizontalGroup(
            SecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecretariaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(SecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecretariaLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel15))
                    .addGroup(SecretariaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        SecretariaLayout.setVerticalGroup(
            SecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecretariaLayout.createSequentialGroup()
                .addGroup(SecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecretariaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel15))
                    .addGroup(SecretariaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Jpanels.add(Secretaria, "card2");

        Direccion.setBackground(new java.awt.Color(153, 153, 153));
        Direccion.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DireccionComponentShown(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(153, 153, 153));
        jLabel21.setFont(new java.awt.Font("Sitka Heading", 1, 60)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Panel de Dirección");

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        ListaDireccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ListaDireccion.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaDireccionComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(ListaDireccion);

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Sitka Subheading", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Padre / Madre");

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));

        Nombre.setBackground(new java.awt.Color(0, 0, 0));
        Nombre.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));

        telefono.setBackground(new java.awt.Color(0, 0, 0));
        telefono.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        telefono.setForeground(new java.awt.Color(255, 255, 255));

        apellidoo.setBackground(new java.awt.Color(0, 0, 0));
        apellidoo.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        apellidoo.setForeground(new java.awt.Color(255, 255, 255));

        telefono1.setBackground(new java.awt.Color(0, 0, 0));
        telefono1.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        telefono1.setForeground(new java.awt.Color(255, 255, 255));
        telefono1.setText("Apellido:");

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nombre:");

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Sitka Subheading", 0, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Amonestaciones");

        telefono2.setBackground(new java.awt.Color(0, 0, 0));
        telefono2.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        telefono2.setForeground(new java.awt.Color(255, 255, 255));
        telefono2.setText("Tlf:");

        telefono3.setBackground(new java.awt.Color(0, 0, 0));
        telefono3.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        telefono3.setForeground(new java.awt.Color(255, 255, 255));
        telefono3.setText("Email:");

        telefono4.setBackground(new java.awt.Color(0, 0, 0));
        telefono4.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        telefono4.setForeground(new java.awt.Color(255, 255, 255));

        amonestacion.setBackground(new java.awt.Color(0, 0, 0));
        amonestacion.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        amonestacion.setForeground(new java.awt.Color(255, 255, 255));
        amonestacion.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefono3)
                            .addComponent(jLabel30)
                            .addComponent(telefono1)
                            .addComponent(telefono2))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(apellidoo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telefono, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(telefono4)
                    .addComponent(amonestacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(jLabel30))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoo)
                    .addComponent(telefono1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(telefono2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(telefono3))
                .addGap(33, 33, 33)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefono4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amonestacion)
                .addGap(25, 25, 25))
        );

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Alumnos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Volver");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setOpaque(true);
        jLabel16.setVerifyInputWhenFocusTarget(false);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16volverainicio(evt);
            }
        });

        javax.swing.GroupLayout DireccionLayout = new javax.swing.GroupLayout(Direccion);
        Direccion.setLayout(DireccionLayout);
        DireccionLayout.setHorizontalGroup(
            DireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DireccionLayout.createSequentialGroup()
                .addGroup(DireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DireccionLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DireccionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel21)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        DireccionLayout.setVerticalGroup(
            DireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DireccionLayout.createSequentialGroup()
                .addGroup(DireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DireccionLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel21))
                    .addGroup(DireccionLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Jpanels.add(Direccion, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secretaria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretaria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secretaria1ActionPerformed

    private void consultarUsuario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarUsuario
        try {
            Statement stmt = conexion.createStatement();

            // Validar las entradas
            String nombre = inputNombre1.getText();
            String apellido = inputApellidos1.getText();
            String tipo = tipoUsuario.getSelection().getActionCommand();

            System.out.print(nombre + apellido + tipo + "-");

            if (nombre == null || apellido == null || tipo == null) {
                JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validar que el tipo es válido
            if (!tipo.equals("Direccion") && !tipo.equals("Secretaria")) {
                JOptionPane.showMessageDialog(null, "Tipo de usuario no válido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ejecutar consulta
            ResultSet rs = stmt.executeQuery("SELECT nombre, apellido FROM " + tipo + ";");
            boolean esta = false;

            while (rs.next()) {
                if (rs.getString("nombre").equalsIgnoreCase(nombre.toLowerCase())
                        && rs.getString("apellido").equalsIgnoreCase(apellido.toLowerCase())) {
                    esta = true;
                    usuario = nombre + " " + apellido;
                }
            }

            // Mapear paneles
            Map<String, JPanel> paneles = new HashMap<>();
            paneles.put("Direccion", Direccion);
            paneles.put("Secretaria", Secretaria);

            JPanel panelSeleccionado = paneles.get(tipo);

            if (esta) {
                Inicio.setVisible(false);
                panelSeleccionado.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Usuario incorrecto", "Error", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_consultarUsuario

    private void ListaDireccionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListaDireccionComponentShown


    }//GEN-LAST:event_ListaDireccionComponentShown

    private void DireccionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DireccionComponentShown
        ListaDireccion.setModel(modelo);
        try {
            Statement stmt = conexion.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT nombre, apellido FROM alumno;");

            if (ListaDireccion.getModel().getSize() > 0) {
                return;
            } else {
                while (rs.next()) {
                    String cont = rs.getString("nombre") + " " + rs.getString("apellido");
                    modelo.addElement(cont);
                    System.out.print(cont);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DireccionComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cont = ListaDireccion.getSelectedValue();
        String[] values = cont.split(" ");
        String nombre = values[0];
        String apellido = values[1];

        try {
            String query = "SELECT padres_id,amonestaciones FROM alumno WHERE nombre = ? AND apellido = ?";
            PreparedStatement stmt = conexion.prepareStatement(query);

            stmt.setString(1, nombre);
            stmt.setString(2, apellido);

            ResultSet rs = stmt.executeQuery();

            // Verifica si hay resultados antes de acceder al rs
            if (rs.next()) {
                int idpadres = rs.getInt("padres_id");
                boolean amon = rs.getBoolean("amonestaciones");

                String[] padres = devolverStringPadres(idpadres).split(" ");

                Nombre.setText(padres[0]);
                apellidoo.setText(padres[1]);
                telefono.setText(padres[2]);
                email.setText(padres[3]);

                if (amon) {
                    amonestacion.setText("Sí");
                } else {
                    amonestacion.setText("No");
                }

            } else {
                // Si no hay resultados, muestra un mensaje de error o advertencia
                JOptionPane.showMessageDialog(null, "No se encontraron padres para este alumno.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListasecretariaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListasecretariaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ListasecretariaComponentShown

    private void mostrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAlumnosActionPerformed
        String cont = Listasecretaria.getSelectedValue();
        String[] values = cont.split(" ");
        String nombre = values[0];
        String apellido = values[1];

        try {
            String query = "SELECT id, matricula_id FROM alumno WHERE nombre = ? AND apellido = ?";
            PreparedStatement stmt = conexion.prepareStatement(query);

            System.out.println("pero");

            stmt.setString(1, nombre);
            stmt.setString(2, apellido);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                int idmat = rs.getInt("matricula_id");
                idAlumnoSeleccionado = rs.getInt("id");
                System.out.println("si tiene next");

                String curso = devolverMatriculaAlumno(idmat);

                this.curso.setText(curso);

            }

        } catch (SQLException e) {

        }
    }//GEN-LAST:event_mostrarAlumnosActionPerformed

    private void SecretariaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SecretariaComponentShown
        Listasecretaria.setModel(modelo);
        try {
            Statement stmt = conexion.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT nombre, apellido FROM alumno;");

            if (Listasecretaria.getModel().getSize() > 0) {
                return;
            } else {
                while (rs.next()) {
                    String cont = rs.getString("nombre") + " " + rs.getString("apellido");
                    modelo.addElement(cont);
                    System.out.print(cont);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SecretariaComponentShown

    private void cambiarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarcursoActionPerformed

        String cursoACambiar = inputcursonuevo.getText();
        String idcursonuevo = "";

        if (cursoACambiar.toLowerCase().equalsIgnoreCase("DAM")) {
            idcursonuevo = "" + 1;
        } else if (cursoACambiar.toLowerCase().equalsIgnoreCase("DAW")) {
            idcursonuevo = "" + 2;
        } else if (cursoACambiar.toLowerCase().equalsIgnoreCase("ASIR")) {
            idcursonuevo = "" + 3;
        } else if (cursoACambiar.toLowerCase().equalsIgnoreCase("SMIR")) {
            idcursonuevo = "" + 4;
        } else if (cursoACambiar.toLowerCase().equalsIgnoreCase("none") || cursoACambiar.toLowerCase().equalsIgnoreCase("")) {
            idcursonuevo = "" + 5;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Introduzca un curso válido.");
            return;
        }

        try {
            String query = "UPDATE alumno SET matricula_id = ? WHERE id = ?;";
            PreparedStatement stmt = conexion.prepareStatement(query);

            stmt.setString(1, idcursonuevo);
            stmt.setString(2, String.valueOf(idAlumnoSeleccionado));

            stmt.executeUpdate();

        } catch (SQLException e) {

        }


    }//GEN-LAST:event_cambiarcursoActionPerformed

    private void volverainicio(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverainicio
        Secretaria.setVisible(false);
        Inicio.setVisible(true);
    }//GEN-LAST:event_volverainicio

    private void jLabel16volverainicio(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16volverainicio
        Direccion.setVisible(false);
        Inicio.setVisible(true);
    }//GEN-LAST:event_jLabel16volverainicio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Direccion;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Jpanels;
    private javax.swing.JList<String> ListaDireccion;
    private javax.swing.JList<String> Listasecretaria;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Secretaria;
    private javax.swing.JLabel amonestacion;
    private javax.swing.JLabel apellidoo;
    private javax.swing.JButton cambiarcurso;
    private javax.swing.JLabel curso;
    private javax.swing.JRadioButton direccion1;
    private javax.swing.JLabel email;
    private javax.swing.JTextPane inputApellidos1;
    private javax.swing.JTextPane inputNombre1;
    private javax.swing.JTextPane inputcursonuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton mostrarAlumnos;
    private javax.swing.JRadioButton secretaria1;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel telefono1;
    private javax.swing.JLabel telefono2;
    private javax.swing.JLabel telefono3;
    private javax.swing.JLabel telefono4;
    private javax.swing.JLabel telefono5;
    private javax.swing.ButtonGroup tipoUsuario;
    // End of variables declaration//GEN-END:variables

    private String devolverStringPadres(int idpadres) throws SQLException {

        String query2 = "SELECT nombre, apellido, telefono, email FROM padresalumno WHERE id = ?";
        PreparedStatement stmt2 = conexion.prepareStatement(query2);
        stmt2.setInt(1, idpadres);

        ResultSet rs2 = stmt2.executeQuery();

        String rsPadres = "";

        // Verifica si hay resultados en el segundo ResultSet
        if (rs2.next()) {
            rsPadres = rs2.getString("nombre")
                    + " " + rs2.getString("apellido")
                    + " " + rs2.getString("telefono")
                    + " " + rs2.getString("email");
        }

        return rsPadres;
    }

    private String devolverMatriculaAlumno(int idmat) {

        String curso = "";

        try {

            String query = "SELECT nombre FROM curso WHERE id = ?";
            PreparedStatement stmt = conexion.prepareStatement(query);
            stmt.setInt(1, idmat);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                curso = rs.getString("nombre");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        return curso;
    }
}
